from __future__ import annotations
from pathlib import Path
from collections import Counter
from datetime import datetime, timezone
import json
from jane_verify.models import ReviewReport, StackProfile

SKIP_DIRS={".git","node_modules","vendor","dist","build","target",".venv","venv","__pycache__"}

class DocumentationGenerator:
    """Generate evidence-based Markdown documentation from source and validation results."""
    def inventory(self, root: str|Path) -> dict:
        root=Path(root).resolve(); counts=Counter(); dirs=Counter(); total=0
        for p in root.rglob('*'):
            try: rel=p.relative_to(root)
            except ValueError: continue
            if any(part in SKIP_DIRS for part in rel.parts): continue
            if p.is_file():
                total+=1; counts[p.suffix.lower() or '[no extension]'] += 1
                if rel.parts: dirs[rel.parts[0]] += 1
        return {"file_count":total,"extensions":dict(counts.most_common(20)),"top_level_areas":dict(dirs.most_common(20))}

    def generate(self, root: str|Path, stack: StackProfile, report: ReviewReport|None=None, findings: list[dict]|None=None) -> str:
        root=Path(root).resolve(); inv=self.inventory(root)
        title=root.name
        lines=[f"# {title} — Generated Project Documentation","",f"Generated by **Jane Verify** at {datetime.now(timezone.utc).isoformat()}.","",
               "## System Overview","",f"Jane Verify detected **{', '.join(stack.languages) or 'no primary language'}**" + (f" with **{', '.join(stack.frameworks)}**." if stack.frameworks else "."),"",
               "## Technology Stack","",f"- Languages: {', '.join(stack.languages) or 'Unknown'}",f"- Frameworks: {', '.join(stack.frameworks) or 'None detected'}",f"- Test frameworks: {', '.join(stack.test_frameworks) or 'None detected'}",f"- Manifests: {', '.join(stack.manifests) or 'None detected'}","",
               "## Repository Inventory","",f"- Files inspected: {inv['file_count']}","", "### Top-level areas"]
        for k,v in inv['top_level_areas'].items(): lines.append(f"- `{k}`: {v} files")
        lines += ["", "### File types"]
        for k,v in inv['extensions'].items(): lines.append(f"- `{k}`: {v}")
        if report:
            lines += ["", "## Validation Summary","",f"- Status: **{report.status.value.upper()}**",f"- Evidence score: **{report.score}/100**",f"- Passed: {report.passed}",f"- Failed: {report.failed}",f"- Skipped: {report.skipped}","", "### Validation checks"]
            for c in report.checks:
                lines.append(f"- **{c.status.value.upper()}** — {c.name} ({c.category})" + (f": {c.reason}" if c.reason else ""))
        if findings is not None:
            lines += ["", "## Code & Security Inspection","", f"Jane Verify reported **{len(findings)} heuristic findings**. Findings are review prompts, not automatic proof of a defect.",""]
            for f in findings[:100]: lines.append(f"- **{f['severity'].upper()} / {f['category']}** `{f['file']}:{f['line']}` — {f['message']}")
        lines += ["", "## Documentation Policy","", "This document is generated from the current source tree and validation evidence. Re-run Jane Verify after material code, dependency, API, database, deployment, or architecture changes to detect documentation drift.",""]
        return "\n".join(lines)

    def write(self, output_dir: str|Path, content: str, filename: str="PROJECT_DOCUMENTATION.md") -> Path:
        out=Path(output_dir).expanduser().resolve(); out.mkdir(parents=True, exist_ok=True)
        path=out/filename; path.write_text(content, encoding='utf-8'); return path
